name: Automated Build Script

on:
  push: 
    branches: [ main ] 

jobs:
  build_on_pelican:
    runs-on: [ pelican02 ]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - name: setup dependencies
        run: |
          . ~/.bashrc
          module load gcc
          export SCRATCH=/scratch/$USER
          export EPOSE_CONDA=/scratch/$USER/.conda/ePose
          conda activate $EPOSE_CONDA
          if [ $? -eq 0 ]; then
            :
          else
            echo "creating & activating python env!"
            conda create --yes python=3.6.8 --prefix $EPOSE_CONDA
            conda activate $EPOSE_CONDA
          fi
          python -V 
          conda env list
          # check that we got an available gpu
          nvidia-smi
          
          cd $GITHUB_WORKSPACE
          echo $PWD
          chmod -R 777 $GITHUB_WORKSPACE
          pip install -r requirements.txt &> /dev/null
          # only install if not already present in the env!
          if ! pip list | grep tensorflow; then
            conda install -y tensorflow-gpu==1.15.0
            python setup.py build_ext --inplace
          fi
          
          export WEIGHTS_DIR=$SCRATCH/weights
          # avoid unnecessary re-downloading
          if ! [ -d $WEIGHTS_DIR ]; then
            # download the datasets & weights from gdrive
            mkdir $SCRATCH/weights
            mkdir $SCRATCH/data
            gdown https://drive.google.com/uc?id=13oki4nUEp3z_6Sl4NovhldB90HZ1w1c- -O $SCRATCH/data/linemod_and_occlusion.zip
            cd $SCRATCH/data
            unzip linemod_and_occlusion.zip
            cd -
            # phi=0 model weights ie the smaller one released by ePose
            gdown https://drive.google.com/uc?id=1naMDN16DW6mfz-kQWM_NwSQGTzX-E9t1 -O $SCRATCH/weights/small_occlusion.h5
          fi
          
          python train.py --phi 0 --epochs 50 occlusion $SCRATCH/data/Linemod_preprocessed/

