name: Automated Build Script

on:
  push: 
    branches: [ main ] 

jobs:
  build_with_gpu:
    runs-on: [ pelican02 ]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - name: setup dependencies
        run: |
          . ~/.bashrc
          export EPOSE_CONDA=/scratch/$USER/.conda/ePose
          conda activate $EPOSE_CONDA
          if [ $? -eq 0 ]; then
            :
          else
            echo "creating & activating python env!"
            conda create --yes python=3.6.8 --prefix $EPOSE_CONDA
            conda activate $EPOSE_CONDA
          fi
          python -V 
          conda env list
          
